server:
  port: 8070
spring:
  application:
    name: cart
  datasource:
    url: jdbc:mysql://localhost:3306/cart?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    timeout: 1000ms
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.cart.pojo
